# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import Any, Dict, List, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .current_bulk_operation import (
    CurrentBulkOperation,
    CurrentBulkOperationCurrentBulkOperation,
)
from .delete_product import DeleteProduct, DeleteProductProductDelete
from .get_customers import GetCustomers, GetCustomersCustomers
from .get_locations import GetLocations, GetLocationsLocations
from .get_order_ids import GetOrderIds, GetOrderIdsOrders
from .get_orders import GetOrders, GetOrdersOrders
from .get_product_ids import GetProductIds, GetProductIdsProducts
from .get_products import GetProducts, GetProductsProducts
from .input_types import (
    MoveInput,
    ProductDeleteInput,
    ProductSetIdentifiers,
    ProductSetInput,
    PublicationInput,
    StagedUploadInput,
)
from .operations import (
    CURRENT_BULK_OPERATION_GQL,
    DELETE_PRODUCT_GQL,
    GET_CUSTOMERS_GQL,
    GET_LOCATIONS_GQL,
    GET_ORDER_IDS_GQL,
    GET_ORDERS_GQL,
    GET_PRODUCT_IDS_GQL,
    GET_PRODUCTS_GQL,
    PRODUCT_REORDER_MEDIA_GQL,
    PRODUCT_SET_BULK_RUN_GQL,
    PRODUCT_SET_GQL,
    STAGED_UPLOADS_CREATE_GQL,
    UPDATE_PUBLICATIONS_GQL,
)
from .product_reorder_media import (
    ProductReorderMedia,
    ProductReorderMediaProductReorderMedia,
)
from .product_set import ProductSet, ProductSetProductSet
from .product_set_bulk_run import (
    ProductSetBulkRun,
    ProductSetBulkRunBulkOperationRunMutation,
)
from .staged_uploads_create import (
    StagedUploadsCreate,
    StagedUploadsCreateStagedUploadsCreate,
)
from .update_publications import (
    UpdatePublications,
    UpdatePublicationsPublishablePublish,
)


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def staged_uploads_create(
        self, input: List[StagedUploadInput], **kwargs: Any
    ) -> Optional[StagedUploadsCreateStagedUploadsCreate]:
        variables: Dict[str, object] = {"input": input}
        response = self.execute(
            query=STAGED_UPLOADS_CREATE_GQL,
            operation_name="StagedUploadsCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return StagedUploadsCreate.model_validate(data).staged_uploads_create

    def product_set_bulk_run(
        self, mutation: str, staged_upload_path: str, **kwargs: Any
    ) -> Optional[ProductSetBulkRunBulkOperationRunMutation]:
        variables: Dict[str, object] = {
            "mutation": mutation,
            "stagedUploadPath": staged_upload_path,
        }
        response = self.execute(
            query=PRODUCT_SET_BULK_RUN_GQL,
            operation_name="ProductSetBulkRun",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductSetBulkRun.model_validate(data).bulk_operation_run_mutation

    def current_bulk_operation(
        self, **kwargs: Any
    ) -> Optional[CurrentBulkOperationCurrentBulkOperation]:
        variables: Dict[str, object] = {}
        response = self.execute(
            query=CURRENT_BULK_OPERATION_GQL,
            operation_name="CurrentBulkOperation",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CurrentBulkOperation.model_validate(data).current_bulk_operation

    def get_customers(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetCustomersCustomers:
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=GET_CUSTOMERS_GQL,
            operation_name="GetCustomers",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetCustomers.model_validate(data).customers

    def get_order_ids(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetOrderIdsOrders:
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=GET_ORDER_IDS_GQL,
            operation_name="GetOrderIds",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetOrderIds.model_validate(data).orders

    def get_orders(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetOrdersOrders:
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=GET_ORDERS_GQL,
            operation_name="GetOrders",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetOrders.model_validate(data).orders

    def get_product_ids(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetProductIdsProducts:
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=GET_PRODUCT_IDS_GQL,
            operation_name="GetProductIds",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetProductIds.model_validate(data).products

    def get_products(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetProductsProducts:
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=GET_PRODUCTS_GQL,
            operation_name="GetProducts",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetProducts.model_validate(data).products

    def get_locations(self, **kwargs: Any) -> GetLocationsLocations:
        variables: Dict[str, object] = {}
        response = self.execute(
            query=GET_LOCATIONS_GQL,
            operation_name="GetLocations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetLocations.model_validate(data).locations

    def product_set(
        self,
        input: ProductSetInput,
        identifier: Union[Optional[ProductSetIdentifiers], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Optional[ProductSetProductSet]:
        variables: Dict[str, object] = {"identifier": identifier, "input": input}
        response = self.execute(
            query=PRODUCT_SET_GQL,
            operation_name="ProductSet",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductSet.model_validate(data).product_set

    def update_publications(
        self, id: str, input: List[PublicationInput], **kwargs: Any
    ) -> Optional[UpdatePublicationsPublishablePublish]:
        variables: Dict[str, object] = {"id": id, "input": input}
        response = self.execute(
            query=UPDATE_PUBLICATIONS_GQL,
            operation_name="UpdatePublications",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdatePublications.model_validate(data).publishable_publish

    def delete_product(
        self,
        input: ProductDeleteInput,
        synchronous: Union[Optional[bool], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Optional[DeleteProductProductDelete]:
        variables: Dict[str, object] = {"input": input, "synchronous": synchronous}
        response = self.execute(
            query=DELETE_PRODUCT_GQL,
            operation_name="DeleteProduct",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return DeleteProduct.model_validate(data).product_delete

    def product_reorder_media(
        self, id: str, moves: List[MoveInput], **kwargs: Any
    ) -> Optional[ProductReorderMediaProductReorderMedia]:
        variables: Dict[str, object] = {"id": id, "moves": moves}
        response = self.execute(
            query=PRODUCT_REORDER_MEDIA_GQL,
            operation_name="ProductReorderMedia",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductReorderMedia.model_validate(data).product_reorder_media
