# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from datetime import datetime
from decimal import Decimal
from typing import Annotated, List, Optional

from odoo.addons.product_connect.services.shopify.helpers import (
    parse_shopify_datetime_to_utc,
)
from pydantic import AnyUrl, BeforeValidator, Field

from .base_model import BaseModel
from .enums import CountryCode, CurrencyCode


class AddressFields(BaseModel):
    id: str
    name: Optional[str]
    address_1: Optional[str] = Field(alias="address1")
    address_2: Optional[str] = Field(alias="address2")
    city: Optional[str]
    province_code: Optional[str] = Field(alias="provinceCode")
    country_code_v_2: Optional[CountryCode] = Field(alias="countryCodeV2")
    zip: Optional[str]
    phone: Optional[str]


class CustomerFields(BaseModel):
    id: str
    first_name: Optional[str] = Field(alias="firstName")
    last_name: Optional[str] = Field(alias="lastName")
    default_email_address: Optional["CustomerFieldsDefaultEmailAddress"] = Field(
        alias="defaultEmailAddress"
    )
    default_phone_number: Optional["CustomerFieldsDefaultPhoneNumber"] = Field(
        alias="defaultPhoneNumber"
    )
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    default_address: Optional["CustomerFieldsDefaultAddress"] = Field(
        alias="defaultAddress"
    )
    addresses_v_2: "CustomerFieldsAddressesV2" = Field(alias="addressesV2")
    tags: List[str]


class CustomerFieldsDefaultEmailAddress(BaseModel):
    email_address: str = Field(alias="emailAddress")


class CustomerFieldsDefaultPhoneNumber(BaseModel):
    phone_number: str = Field(alias="phoneNumber")


class CustomerFieldsDefaultAddress(AddressFields):
    pass


class CustomerFieldsAddressesV2(BaseModel):
    nodes: List["CustomerFieldsAddressesV2Nodes"]


class CustomerFieldsAddressesV2Nodes(AddressFields):
    pass


class MediaImageFields(BaseModel):
    id: str
    alt: Optional[str]
    original_source: Optional["MediaImageFieldsOriginalSource"] = Field(
        alias="originalSource"
    )
    preview: Optional["MediaImageFieldsPreview"]


class MediaImageFieldsOriginalSource(BaseModel):
    url: Optional[AnyUrl]


class MediaImageFieldsPreview(BaseModel):
    image: Optional["MediaImageFieldsPreviewImage"]


class MediaImageFieldsPreviewImage(BaseModel):
    url: AnyUrl


class MetafieldFields(BaseModel):
    id: str
    key: str
    value: str


class MoneyFields(BaseModel):
    amount: Decimal
    currency_code: CurrencyCode = Field(alias="currencyCode")


class OrderLineItemFields(BaseModel):
    id: str
    sku: Optional[str]
    quantity: int
    name: str
    variant: Optional["OrderLineItemFieldsVariant"]
    original_unit_price_set: "OrderLineItemFieldsOriginalUnitPriceSet" = Field(
        alias="originalUnitPriceSet"
    )
    custom_attributes: List["OrderLineItemFieldsCustomAttributes"] = Field(
        alias="customAttributes"
    )


class OrderLineItemFieldsVariant(BaseModel):
    id: str


class OrderLineItemFieldsOriginalUnitPriceSet(BaseModel):
    presentment_money: "OrderLineItemFieldsOriginalUnitPriceSetPresentmentMoney" = (
        Field(alias="presentmentMoney")
    )
    shop_money: "OrderLineItemFieldsOriginalUnitPriceSetShopMoney" = Field(
        alias="shopMoney"
    )


class OrderLineItemFieldsOriginalUnitPriceSetPresentmentMoney(MoneyFields):
    pass


class OrderLineItemFieldsOriginalUnitPriceSetShopMoney(MoneyFields):
    pass


class OrderLineItemFieldsCustomAttributes(BaseModel):
    key: str
    value: Optional[str]


class OrderFields(BaseModel):
    id: str
    name: str
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    processed_at: Annotated[
        datetime, BeforeValidator(parse_shopify_datetime_to_utc)
    ] = Field(alias="processedAt")
    closed_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="closedAt")
    cancelled_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="cancelledAt")
    currency_code: CurrencyCode = Field(alias="currencyCode")
    total_price_set: "OrderFieldsTotalPriceSet" = Field(alias="totalPriceSet")
    subtotal_price_set: Optional["OrderFieldsSubtotalPriceSet"] = Field(
        alias="subtotalPriceSet"
    )
    total_shipping_price_set: "OrderFieldsTotalShippingPriceSet" = Field(
        alias="totalShippingPriceSet"
    )
    customer: Optional["OrderFieldsCustomer"]
    shipping_address: Optional["OrderFieldsShippingAddress"] = Field(
        alias="shippingAddress"
    )
    billing_address: Optional["OrderFieldsBillingAddress"] = Field(
        alias="billingAddress"
    )
    line_items: "OrderFieldsLineItems" = Field(alias="lineItems")
    metafields: "OrderFieldsMetafields"


class OrderFieldsTotalPriceSet(BaseModel):
    presentment_money: "OrderFieldsTotalPriceSetPresentmentMoney" = Field(
        alias="presentmentMoney"
    )


class OrderFieldsTotalPriceSetPresentmentMoney(MoneyFields):
    pass


class OrderFieldsSubtotalPriceSet(BaseModel):
    presentment_money: "OrderFieldsSubtotalPriceSetPresentmentMoney" = Field(
        alias="presentmentMoney"
    )


class OrderFieldsSubtotalPriceSetPresentmentMoney(MoneyFields):
    pass


class OrderFieldsTotalShippingPriceSet(BaseModel):
    presentment_money: "OrderFieldsTotalShippingPriceSetPresentmentMoney" = Field(
        alias="presentmentMoney"
    )


class OrderFieldsTotalShippingPriceSetPresentmentMoney(MoneyFields):
    pass


class OrderFieldsCustomer(CustomerFields):
    pass


class OrderFieldsShippingAddress(AddressFields):
    pass


class OrderFieldsBillingAddress(AddressFields):
    pass


class OrderFieldsLineItems(BaseModel):
    nodes: List["OrderFieldsLineItemsNodes"]


class OrderFieldsLineItemsNodes(OrderLineItemFields):
    pass


class OrderFieldsMetafields(BaseModel):
    nodes: List["OrderFieldsMetafieldsNodes"]


class OrderFieldsMetafieldsNodes(MetafieldFields):
    pass


class UserErrorFields(BaseModel):
    field: Optional[List[str]]
    message: str


class VariantFields(BaseModel):
    id: str
    price: Decimal
    sku: Optional[str]
    barcode: Optional[str]
    inventory_item: "VariantFieldsInventoryItem" = Field(alias="inventoryItem")


class VariantFieldsInventoryItem(BaseModel):
    unit_cost: Optional["VariantFieldsInventoryItemUnitCost"] = Field(alias="unitCost")
    measurement: "VariantFieldsInventoryItemMeasurement"


class VariantFieldsInventoryItemUnitCost(BaseModel):
    amount: Decimal
    currency_code: CurrencyCode = Field(alias="currencyCode")


class VariantFieldsInventoryItemMeasurement(BaseModel):
    weight: Optional["VariantFieldsInventoryItemMeasurementWeight"]


class VariantFieldsInventoryItemMeasurementWeight(BaseModel):
    value: float


AddressFields.model_rebuild()
CustomerFields.model_rebuild()
MediaImageFields.model_rebuild()
MetafieldFields.model_rebuild()
MoneyFields.model_rebuild()
OrderLineItemFields.model_rebuild()
OrderFields.model_rebuild()
UserErrorFields.model_rebuild()
VariantFields.model_rebuild()
