# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from datetime import datetime
from decimal import Decimal
from typing import Annotated, List, Literal, Optional, Union

from pydantic import AnyUrl, BeforeValidator, Field

from ..helpers import parse_shopify_datetime_to_utc
from .base_model import BaseModel
from .enums import (
    CountryCode,
    CurrencyCode,
    CustomerEmailAddressMarketingState,
    CustomerMarketingOptInLevel,
    CustomerSmsMarketingState,
    MediaStatus,
    ProductStatus,
)


class AddressFields(BaseModel):
    id: str
    company: Optional[str]
    name: Optional[str]
    address_1: Optional[str] = Field(alias="address1")
    address_2: Optional[str] = Field(alias="address2")
    city: Optional[str]
    province_code: Optional[str] = Field(alias="provinceCode")
    province: Optional[str]
    country_code_v_2: Optional[CountryCode] = Field(alias="countryCodeV2")
    zip: Optional[str]
    phone: Optional[str]


class CustomerFields(BaseModel):
    id: str
    first_name: Optional[str] = Field(alias="firstName")
    last_name: Optional[str] = Field(alias="lastName")
    default_email_address: Optional["CustomerFieldsDefaultEmailAddress"] = Field(
        alias="defaultEmailAddress"
    )
    default_phone_number: Optional["CustomerFieldsDefaultPhoneNumber"] = Field(
        alias="defaultPhoneNumber"
    )
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    default_address: Optional["CustomerFieldsDefaultAddress"] = Field(
        alias="defaultAddress"
    )
    addresses_v_2: "CustomerFieldsAddressesV2" = Field(alias="addressesV2")
    tags: List[str]
    tax_exempt: bool = Field(alias="taxExempt")


class CustomerFieldsDefaultEmailAddress(BaseModel):
    email_address: str = Field(alias="emailAddress")
    marketing_state: CustomerEmailAddressMarketingState = Field(alias="marketingState")
    marketing_opt_in_level: Optional[CustomerMarketingOptInLevel] = Field(
        alias="marketingOptInLevel"
    )
    marketing_updated_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="marketingUpdatedAt")


class CustomerFieldsDefaultPhoneNumber(BaseModel):
    phone_number: str = Field(alias="phoneNumber")
    marketing_state: CustomerSmsMarketingState = Field(alias="marketingState")
    marketing_opt_in_level: Optional[CustomerMarketingOptInLevel] = Field(
        alias="marketingOptInLevel"
    )
    marketing_updated_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="marketingUpdatedAt")


class CustomerFieldsDefaultAddress(AddressFields):
    pass


class CustomerFieldsAddressesV2(BaseModel):
    nodes: List["CustomerFieldsAddressesV2Nodes"]


class CustomerFieldsAddressesV2Nodes(AddressFields):
    pass


class FulfillmentTrackingInfoFields(BaseModel):
    number: Optional[str]
    url: Optional[AnyUrl]
    company: Optional[str]


class MediaImageFields(BaseModel):
    typename__: str = Field(alias="__typename")
    id: str
    alt: Optional[str]
    original_source: Optional["MediaImageFieldsOriginalSource"] = Field(
        alias="originalSource"
    )
    preview: Optional["MediaImageFieldsPreview"]


class MediaImageFieldsOriginalSource(BaseModel):
    url: Optional[AnyUrl]


class MediaImageFieldsPreview(BaseModel):
    image: Optional["MediaImageFieldsPreviewImage"]


class MediaImageFieldsPreviewImage(BaseModel):
    url: AnyUrl


class MetafieldFields(BaseModel):
    id: str
    key: str
    value: str


class MoneyFields(BaseModel):
    amount: Decimal
    currency_code: CurrencyCode = Field(alias="currencyCode")


class MoneyBagFields(BaseModel):
    presentment_money: "MoneyBagFieldsPresentmentMoney" = Field(
        alias="presentmentMoney"
    )
    shop_money: "MoneyBagFieldsShopMoney" = Field(alias="shopMoney")


class MoneyBagFieldsPresentmentMoney(MoneyFields):
    pass


class MoneyBagFieldsShopMoney(MoneyFields):
    pass


class ShippingLineFields(BaseModel):
    id: Optional[str]
    title: str
    carrier_identifier: Optional[str] = Field(alias="carrierIdentifier")
    code: Optional[str]
    original_price_set: "ShippingLineFieldsOriginalPriceSet" = Field(
        alias="originalPriceSet"
    )
    current_discounted_price_set: "ShippingLineFieldsCurrentDiscountedPriceSet" = Field(
        alias="currentDiscountedPriceSet"
    )
    discounted_price_set: "ShippingLineFieldsDiscountedPriceSet" = Field(
        alias="discountedPriceSet"
    )
    delivery_category: Optional[str] = Field(alias="deliveryCategory")
    is_removed: bool = Field(alias="isRemoved")


class ShippingLineFieldsOriginalPriceSet(MoneyBagFields):
    pass


class ShippingLineFieldsCurrentDiscountedPriceSet(MoneyBagFields):
    pass


class ShippingLineFieldsDiscountedPriceSet(MoneyBagFields):
    pass


class OrderLineItemFields(BaseModel):
    id: str
    sku: Optional[str]
    quantity: int
    name: str
    variant: Optional["OrderLineItemFieldsVariant"]
    original_unit_price_set: "OrderLineItemFieldsOriginalUnitPriceSet" = Field(
        alias="originalUnitPriceSet"
    )
    custom_attributes: List["OrderLineItemFieldsCustomAttributes"] = Field(
        alias="customAttributes"
    )
    discount_allocations: List["OrderLineItemFieldsDiscountAllocations"] = Field(
        alias="discountAllocations"
    )


class OrderLineItemFieldsVariant(BaseModel):
    id: str


class OrderLineItemFieldsOriginalUnitPriceSet(MoneyBagFields):
    pass


class OrderLineItemFieldsCustomAttributes(BaseModel):
    key: str
    value: Optional[str]


class OrderLineItemFieldsDiscountAllocations(BaseModel):
    allocated_amount_set: "OrderLineItemFieldsDiscountAllocationsAllocatedAmountSet" = (
        Field(alias="allocatedAmountSet")
    )


class OrderLineItemFieldsDiscountAllocationsAllocatedAmountSet(MoneyBagFields):
    pass


class TaxLineFields(BaseModel):
    title: str
    rate_percentage: Optional[float] = Field(alias="ratePercentage")
    price_set: "TaxLineFieldsPriceSet" = Field(alias="priceSet")


class TaxLineFieldsPriceSet(MoneyBagFields):
    pass


class OrderFields(BaseModel):
    id: str
    name: str
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    processed_at: Annotated[
        datetime, BeforeValidator(parse_shopify_datetime_to_utc)
    ] = Field(alias="processedAt")
    closed_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="closedAt")
    cancelled_at: Optional[
        Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)]
    ] = Field(alias="cancelledAt")
    currency_code: CurrencyCode = Field(alias="currencyCode")
    total_price_set: "OrderFieldsTotalPriceSet" = Field(alias="totalPriceSet")
    subtotal_price_set: Optional["OrderFieldsSubtotalPriceSet"] = Field(
        alias="subtotalPriceSet"
    )
    total_shipping_price_set: "OrderFieldsTotalShippingPriceSet" = Field(
        alias="totalShippingPriceSet"
    )
    customer: Optional["OrderFieldsCustomer"]
    shipping_address: Optional["OrderFieldsShippingAddress"] = Field(
        alias="shippingAddress"
    )
    billing_address: Optional["OrderFieldsBillingAddress"] = Field(
        alias="billingAddress"
    )
    line_items: "OrderFieldsLineItems" = Field(alias="lineItems")
    shipping_lines: "OrderFieldsShippingLines" = Field(alias="shippingLines")
    fulfillments: List["OrderFieldsFulfillments"]
    discount_applications: "OrderFieldsDiscountApplications" = Field(
        alias="discountApplications"
    )
    total_discounts_set: Optional["OrderFieldsTotalDiscountsSet"] = Field(
        alias="totalDiscountsSet"
    )
    tax_lines: List["OrderFieldsTaxLines"] = Field(alias="taxLines")
    metafields: "OrderFieldsMetafields"
    note: Optional[str]
    custom_attributes: List["OrderFieldsCustomAttributes"] = Field(
        alias="customAttributes"
    )
    payment_gateway_names: List[str] = Field(alias="paymentGatewayNames")


class OrderFieldsTotalPriceSet(MoneyBagFields):
    pass


class OrderFieldsSubtotalPriceSet(MoneyBagFields):
    pass


class OrderFieldsTotalShippingPriceSet(MoneyBagFields):
    pass


class OrderFieldsCustomer(CustomerFields):
    pass


class OrderFieldsShippingAddress(AddressFields):
    pass


class OrderFieldsBillingAddress(AddressFields):
    pass


class OrderFieldsLineItems(BaseModel):
    nodes: List["OrderFieldsLineItemsNodes"]


class OrderFieldsLineItemsNodes(OrderLineItemFields):
    pass


class OrderFieldsShippingLines(BaseModel):
    nodes: List["OrderFieldsShippingLinesNodes"]


class OrderFieldsShippingLinesNodes(ShippingLineFields):
    pass


class OrderFieldsFulfillments(BaseModel):
    tracking_info: List["OrderFieldsFulfillmentsTrackingInfo"] = Field(
        alias="trackingInfo"
    )


class OrderFieldsFulfillmentsTrackingInfo(FulfillmentTrackingInfoFields):
    pass


class OrderFieldsDiscountApplications(BaseModel):
    nodes: List[
        Annotated[
            Union[
                "OrderFieldsDiscountApplicationsNodesDiscountApplication",
                "OrderFieldsDiscountApplicationsNodesDiscountCodeApplication",
                "OrderFieldsDiscountApplicationsNodesManualDiscountApplication",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class OrderFieldsDiscountApplicationsNodesDiscountApplication(BaseModel):
    typename__: Literal[
        "AutomaticDiscountApplication",
        "DiscountApplication",
        "ScriptDiscountApplication",
    ] = Field(alias="__typename")


class OrderFieldsDiscountApplicationsNodesDiscountCodeApplication(BaseModel):
    typename__: Literal["DiscountCodeApplication"] = Field(alias="__typename")
    code: str


class OrderFieldsDiscountApplicationsNodesManualDiscountApplication(BaseModel):
    typename__: Literal["ManualDiscountApplication"] = Field(alias="__typename")
    title: str


class OrderFieldsTotalDiscountsSet(MoneyBagFields):
    pass


class OrderFieldsTaxLines(TaxLineFields):
    pass


class OrderFieldsMetafields(BaseModel):
    nodes: List["OrderFieldsMetafieldsNodes"]


class OrderFieldsMetafieldsNodes(MetafieldFields):
    pass


class OrderFieldsCustomAttributes(BaseModel):
    key: str
    value: Optional[str]


class VariantFields(BaseModel):
    id: str
    price: Decimal
    sku: Optional[str]
    barcode: Optional[str]
    inventory_item: "VariantFieldsInventoryItem" = Field(alias="inventoryItem")


class VariantFieldsInventoryItem(BaseModel):
    unit_cost: Optional["VariantFieldsInventoryItemUnitCost"] = Field(alias="unitCost")
    measurement: "VariantFieldsInventoryItemMeasurement"


class VariantFieldsInventoryItemUnitCost(BaseModel):
    amount: Decimal
    currency_code: CurrencyCode = Field(alias="currencyCode")


class VariantFieldsInventoryItemMeasurement(BaseModel):
    weight: Optional["VariantFieldsInventoryItemMeasurementWeight"]


class VariantFieldsInventoryItemMeasurementWeight(BaseModel):
    value: float


class ProductFields(BaseModel):
    id: str
    title: str
    description_html: str = Field(alias="descriptionHtml")
    vendor: str
    product_type: str = Field(alias="productType")
    status: ProductStatus
    total_inventory: int = Field(alias="totalInventory")
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    media: "ProductFieldsMedia"
    variants: "ProductFieldsVariants"
    metafields: "ProductFieldsMetafields"


class ProductFieldsMedia(BaseModel):
    nodes: List[
        Annotated[
            Union["ProductFieldsMediaNodesMedia", "ProductFieldsMediaNodesMediaImage"],
            Field(discriminator="typename__"),
        ]
    ]


class ProductFieldsMediaNodesMedia(BaseModel):
    typename__: Literal["ExternalVideo", "Media", "Model3d", "Video"] = Field(
        alias="__typename"
    )
    status: MediaStatus


class ProductFieldsMediaNodesMediaImage(MediaImageFields):
    typename__: Literal["MediaImage"] = Field(alias="__typename")
    status: MediaStatus


class ProductFieldsVariants(BaseModel):
    nodes: List["ProductFieldsVariantsNodes"]


class ProductFieldsVariantsNodes(VariantFields):
    pass


class ProductFieldsMetafields(BaseModel):
    nodes: List["ProductFieldsMetafieldsNodes"]


class ProductFieldsMetafieldsNodes(MetafieldFields):
    pass


class UserErrorFields(BaseModel):
    field: Optional[List[str]]
    message: str


AddressFields.model_rebuild()
CustomerFields.model_rebuild()
FulfillmentTrackingInfoFields.model_rebuild()
MediaImageFields.model_rebuild()
MetafieldFields.model_rebuild()
MoneyFields.model_rebuild()
MoneyBagFields.model_rebuild()
ShippingLineFields.model_rebuild()
OrderLineItemFields.model_rebuild()
TaxLineFields.model_rebuild()
OrderFields.model_rebuild()
VariantFields.model_rebuild()
ProductFields.model_rebuild()
UserErrorFields.model_rebuild()
