# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import OrderFields


class GetOrders(BaseModel):
    orders: "GetOrdersOrders"


class GetOrdersOrders(BaseModel):
    page_info: "GetOrdersOrdersPageInfo" = Field(alias="pageInfo")
    nodes: List["GetOrdersOrdersNodes"]


class GetOrdersOrdersPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetOrdersOrdersNodes(OrderFields):
    pass


GetOrders.model_rebuild()
GetOrdersOrders.model_rebuild()
