# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetProductIds(BaseModel):
    products: "GetProductIdsProducts"


class GetProductIdsProducts(BaseModel):
    page_info: "GetProductIdsProductsPageInfo" = Field(alias="pageInfo")
    nodes: List["GetProductIdsProductsNodes"]


class GetProductIdsProductsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetProductIdsProductsNodes(BaseModel):
    id: str


GetProductIds.model_rebuild()
GetProductIdsProducts.model_rebuild()
