# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from datetime import datetime
from typing import Annotated, List, Literal, Optional, Union

from odoo.addons.product_connect.services.shopify.helpers import (
    parse_shopify_datetime_to_utc,
)
from pydantic import BeforeValidator, Field

from .base_model import BaseModel
from .enums import MediaStatus, ProductStatus
from .fragments import MediaImageFields, MetafieldFields, VariantFields


class GetProducts(BaseModel):
    products: "GetProductsProducts"


class GetProductsProducts(BaseModel):
    page_info: "GetProductsProductsPageInfo" = Field(alias="pageInfo")
    nodes: List["GetProductsProductsNodes"]


class GetProductsProductsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetProductsProductsNodes(BaseModel):
    id: str
    title: str
    description_html: str = Field(alias="descriptionHtml")
    vendor: str
    product_type: str = Field(alias="productType")
    status: ProductStatus
    total_inventory: int = Field(alias="totalInventory")
    created_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="createdAt")
    )
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    media: "GetProductsProductsNodesMedia"
    variants: "GetProductsProductsNodesVariants"
    metafields: "GetProductsProductsNodesMetafields"


class GetProductsProductsNodesMedia(BaseModel):
    nodes: List[
        Annotated[
            Union[
                "GetProductsProductsNodesMediaNodesMedia",
                "GetProductsProductsNodesMediaNodesMediaImage",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class GetProductsProductsNodesMediaNodesMedia(BaseModel):
    typename__: Literal["ExternalVideo", "Media", "Model3d", "Video"] = Field(
        alias="__typename"
    )
    status: MediaStatus


class GetProductsProductsNodesMediaNodesMediaImage(MediaImageFields):
    typename__: Literal["MediaImage"] = Field(alias="__typename")
    status: MediaStatus


class GetProductsProductsNodesVariants(BaseModel):
    nodes: List["GetProductsProductsNodesVariantsNodes"]


class GetProductsProductsNodesVariantsNodes(VariantFields):
    pass


class GetProductsProductsNodesMetafields(BaseModel):
    nodes: List["GetProductsProductsNodesMetafieldsNodes"]


class GetProductsProductsNodesMetafieldsNodes(MetafieldFields):
    pass


GetProducts.model_rebuild()
GetProductsProducts.model_rebuild()
GetProductsProductsNodes.model_rebuild()
GetProductsProductsNodesMedia.model_rebuild()
GetProductsProductsNodesVariants.model_rebuild()
GetProductsProductsNodesMetafields.model_rebuild()
