# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProductFields


class GetProducts(BaseModel):
    products: "GetProductsProducts"


class GetProductsProducts(BaseModel):
    page_info: "GetProductsProductsPageInfo" = Field(alias="pageInfo")
    nodes: List["GetProductsProductsNodes"]


class GetProductsProductsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetProductsProductsNodes(ProductFields):
    pass


GetProducts.model_rebuild()
GetProductsProducts.model_rebuild()
