# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from datetime import datetime
from typing import Annotated, List, Literal, Optional, Union

from pydantic import BeforeValidator, Field

from ..helpers import parse_shopify_datetime_to_utc
from .base_model import BaseModel
from .enums import MediaStatus
from .fragments import MediaImageFields, MetafieldFields, VariantFields


class ProductSet(BaseModel):
    product_set: Optional["ProductSetProductSet"] = Field(alias="productSet")


class ProductSetProductSet(BaseModel):
    product: Optional["ProductSetProductSetProduct"]
    user_errors: List["ProductSetProductSetUserErrors"] = Field(alias="userErrors")


class ProductSetProductSetProduct(BaseModel):
    id: str
    updated_at: Annotated[datetime, BeforeValidator(parse_shopify_datetime_to_utc)] = (
        Field(alias="updatedAt")
    )
    variants: "ProductSetProductSetProductVariants"
    metafields: "ProductSetProductSetProductMetafields"
    media: "ProductSetProductSetProductMedia"
    resource_publications_v_2: "ProductSetProductSetProductResourcePublicationsV2" = (
        Field(alias="resourcePublicationsV2")
    )


class ProductSetProductSetProductVariants(BaseModel):
    nodes: List["ProductSetProductSetProductVariantsNodes"]


class ProductSetProductSetProductVariantsNodes(VariantFields):
    pass


class ProductSetProductSetProductMetafields(BaseModel):
    nodes: List["ProductSetProductSetProductMetafieldsNodes"]


class ProductSetProductSetProductMetafieldsNodes(MetafieldFields):
    pass


class ProductSetProductSetProductMedia(BaseModel):
    nodes: List[
        Annotated[
            Union[
                "ProductSetProductSetProductMediaNodesMedia",
                "ProductSetProductSetProductMediaNodesMediaImage",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class ProductSetProductSetProductMediaNodesMedia(BaseModel):
    typename__: Literal["ExternalVideo", "Media", "Model3d", "Video"] = Field(
        alias="__typename"
    )
    status: MediaStatus


class ProductSetProductSetProductMediaNodesMediaImage(MediaImageFields):
    typename__: Literal["MediaImage"] = Field(alias="__typename")
    status: MediaStatus


class ProductSetProductSetProductResourcePublicationsV2(BaseModel):
    nodes: List["ProductSetProductSetProductResourcePublicationsV2Nodes"]


class ProductSetProductSetProductResourcePublicationsV2Nodes(BaseModel):
    publication: "ProductSetProductSetProductResourcePublicationsV2NodesPublication"


class ProductSetProductSetProductResourcePublicationsV2NodesPublication(BaseModel):
    id: str


class ProductSetProductSetUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


ProductSet.model_rebuild()
ProductSetProductSet.model_rebuild()
ProductSetProductSetProduct.model_rebuild()
ProductSetProductSetProductVariants.model_rebuild()
ProductSetProductSetProductMetafields.model_rebuild()
ProductSetProductSetProductMedia.model_rebuild()
ProductSetProductSetProductResourcePublicationsV2.model_rebuild()
ProductSetProductSetProductResourcePublicationsV2Nodes.model_rebuild()
