# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class ProductSetBulkRun(BaseModel):
    bulk_operation_run_mutation: Optional[
        "ProductSetBulkRunBulkOperationRunMutation"
    ] = Field(alias="bulkOperationRunMutation")


class ProductSetBulkRunBulkOperationRunMutation(BaseModel):
    bulk_operation: Optional[
        "ProductSetBulkRunBulkOperationRunMutationBulkOperation"
    ] = Field(alias="bulkOperation")
    user_errors: List["ProductSetBulkRunBulkOperationRunMutationUserErrors"] = Field(
        alias="userErrors"
    )


class ProductSetBulkRunBulkOperationRunMutationBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus


class ProductSetBulkRunBulkOperationRunMutationUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


ProductSetBulkRun.model_rebuild()
ProductSetBulkRunBulkOperationRunMutation.model_rebuild()
