# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel


class StagedUploadsCreate(BaseModel):
    staged_uploads_create: Optional["StagedUploadsCreateStagedUploadsCreate"] = Field(
        alias="stagedUploadsCreate"
    )


class StagedUploadsCreateStagedUploadsCreate(BaseModel):
    staged_targets: Optional[
        List["StagedUploadsCreateStagedUploadsCreateStagedTargets"]
    ] = Field(alias="stagedTargets")
    user_errors: List["StagedUploadsCreateStagedUploadsCreateUserErrors"] = Field(
        alias="userErrors"
    )


class StagedUploadsCreateStagedUploadsCreateStagedTargets(BaseModel):
    url: Optional[AnyUrl]
    parameters: List["StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters"]
    resource_url: Optional[AnyUrl] = Field(alias="resourceUrl")


class StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters(BaseModel):
    name: str
    value: str


class StagedUploadsCreateStagedUploadsCreateUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


StagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreateStagedTargets.model_rebuild()
