{
    "name": "Product Connect Module",
    "version": "18.0.8.0",
    "category": "Industries",
    "author": "Chris Busillo",
    "company": "Shiny Computers",
    "website": "https://www.shinycomputers.com",
    "depends": [
        "base",
        "product",
        "web",
        "web_tour",
        "website_sale",
        "base_automation",
        "stock",
        "mail",
        "project",
        "repair",
        "contacts",
        "account",
        "sale_management",
        "purchase",
        "phone_validation",
        "delivery",
        "delivery_ups_rest",
        "delivery_usps_rest",
        "base_geolocalize",
    ],
    "description": "Module to connect to various product sources and manage product data for motor parts.",
    "data": [
        "data/motor_test_section_data.xml",  # motor data order is important (relations)
        "data/motor_test_selection_data.xml",
        "data/motor_test_template_data.xml",
        "data/motor_part_template_data.xml",
        "data/motor_stat_data.xml",
        "data/product_condition_data.xml",
        "data/res_config_data.xml",
        "data/mail_templates.xml",
        "data/delivery_products.xml",  # delivery data order is important (relations)
        "data/delivery_carriers.xml",
        "data/delivery_carrier_mappings.xml",
        "report/motor_product_reports.xml",
        "report/motor_reports.xml",
        "report/product_reports.xml",
        "views/delivery_carrier_views.xml",
        "views/motor_views.xml",  # motor_views needs to be loaded first (menu parent)
        "views/motor_part_template_views.xml",
        "views/motor_product_template_views.xml",
        "views/motor_product_views.xml",
        "views/motor_test_template_views.xml",
        "views/motor_test_selection_views.xml",
        "views/motor_test_section_views.xml",
        "views/printnode_interface_views.xml",
        "views/product_color_views.xml",
        "views/product_condition_views.xml",
        "views/product_import_views.xml",
        "views/product_inventory_wizard_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/product_processing_views.xml",
        "views/product_image_views.xml",
        "views/product_type_views.xml",
        "views/product_manufacturer_views.xml",
        "views/repair_order_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/shipping_analytics_views.xml",
        "views/shopify_sync_views.xml",
        "security/ir.model.access.csv",
    ],
    "assets": {
        "web.assets_backend": [
            "product_connect/static/src/js/external/qr-scanner.umd.min.js",
            "product_connect/static/src/scss/*",
            "product_connect/static/src/js/forms/*",
            "product_connect/static/src/js/lists/*",
            "product_connect/static/src/js/utils/*",
            "product_connect/static/src/js/widgets/*",
            "product_connect/static/src/xml/*",
        ],
        "web.assets_backend_lazy": [
            "product_connect/static/src/views/multigraph/*.js",
            "product_connect/static/src/views/multigraph/*.xml",
        ],
        "web.assets_unit_tests": [
            "product_connect/static/tests/**/*.test.js",
        ],
        "web.assets_tests": [
            "product_connect/static/tests/tours/**/*.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
