# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetOrderIds(BaseModel):
    orders: "GetOrderIdsOrders"


class GetOrderIdsOrders(BaseModel):
    page_info: "GetOrderIdsOrdersPageInfo" = Field(alias="pageInfo")
    nodes: List["GetOrderIdsOrdersNodes"]


class GetOrderIdsOrdersPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetOrderIdsOrdersNodes(BaseModel):
    id: str


GetOrderIds.model_rebuild()
GetOrderIdsOrders.model_rebuild()
