# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Any, Dict, List, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .delete_product import DeleteProduct
from .get_bulk_operation_status import GetBulkOperationStatus
from .get_locations import GetLocations
from .get_product_ids import GetProductIds
from .get_products import GetProducts
from .input_types import (
    ProductDeleteInput,
    ProductSetIdentifiers,
    ProductSetInput,
    PublicationInput,
)
from .product_set import ProductSet
from .run_bulk_operation import RunBulkOperation
from .update_publications import UpdatePublications


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def run_bulk_operation(
        self, mutation: str, staged_upload_path: str, **kwargs: Any
    ) -> RunBulkOperation:
        query = gql(
            """
            mutation RunBulkOperation($mutation: String!, $stagedUploadPath: String!) {
              bulkOperationRunMutation(
                mutation: $mutation
                stagedUploadPath: $stagedUploadPath
              ) {
                bulkOperation {
                  id
                  status
                }
                userErrors {
                  field
                  message
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "mutation": mutation,
            "stagedUploadPath": staged_upload_path,
        }
        response = self.execute(
            query=query,
            operation_name="RunBulkOperation",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return RunBulkOperation.model_validate(data)

    def get_bulk_operation_status(self, **kwargs: Any) -> GetBulkOperationStatus:
        query = gql(
            """
            query GetBulkOperationStatus {
              currentBulkOperation {
                id
                status
                errorCode
                createdAt
                completedAt
                objectCount
                fileSize
                url
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetBulkOperationStatus",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetBulkOperationStatus.model_validate(data)

    def get_product_ids(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetProductIds:
        _query = gql(
            """
            query GetProductIds($cursor: String, $limit: Int!, $query: String) {
              products(first: $limit, after: $cursor, query: $query) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                edges {
                  cursor
                  node {
                    id
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=_query, operation_name="GetProductIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetProductIds.model_validate(data)

    def get_products(
        self,
        limit: int,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        query: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetProducts:
        _query = gql(
            """
            query GetProducts($cursor: String, $limit: Int!, $query: String) {
              products(first: $limit, after: $cursor, query: $query) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                edges {
                  cursor
                  node {
                    id
                    title
                    descriptionHtml
                    vendor
                    productType
                    status
                    totalInventory
                    createdAt
                    updatedAt
                    media(first: 20) {
                      edges {
                        node {
                          __typename
                          alt
                          preview {
                            image {
                              url
                            }
                          }
                        }
                      }
                    }
                    variants(first: 1) {
                      edges {
                        node {
                          id
                          price
                          sku
                          barcode
                          inventoryItem {
                            unitCost {
                              amount
                              currencyCode
                            }
                            measurement {
                              weight {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                    metafields(first: 15, namespace: "custom") {
                      edges {
                        node {
                          id
                          key
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "cursor": cursor,
            "limit": limit,
            "query": query,
        }
        response = self.execute(
            query=_query, operation_name="GetProducts", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetProducts.model_validate(data)

    def get_locations(self, **kwargs: Any) -> GetLocations:
        query = gql(
            """
            query GetLocations {
              locations(first: 5) {
                edges {
                  node {
                    id
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetLocations", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetLocations.model_validate(data)

    def product_set(
        self,
        input: ProductSetInput,
        identifier: Union[Optional[ProductSetIdentifiers], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ProductSet:
        query = gql(
            """
            mutation ProductSet($identifier: ProductSetIdentifiers, $input: ProductSetInput!) {
              productSet(identifier: $identifier, input: $input) {
                product {
                  id
                  variants(first: 1) {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                  metafields(first: 15, namespace: "custom") {
                    edges {
                      node {
                        id
                        key
                      }
                    }
                  }
                  resourcePublicationsV2(onlyPublished: true, first: 10) {
                    edges {
                      node {
                        publication {
                          id
                        }
                      }
                    }
                  }
                }
                userErrors {
                  field
                  message
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"identifier": identifier, "input": input}
        response = self.execute(
            query=query, operation_name="ProductSet", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductSet.model_validate(data)

    def update_publications(
        self, id: str, input: List[PublicationInput], **kwargs: Any
    ) -> UpdatePublications:
        query = gql(
            """
            mutation UpdatePublications($id: ID!, $input: [PublicationInput!]!) {
              publishablePublish(id: $id, input: $input) {
                userErrors {
                  field
                  message
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "input": input}
        response = self.execute(
            query=query,
            operation_name="UpdatePublications",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdatePublications.model_validate(data)

    def delete_product(self, input: ProductDeleteInput, **kwargs: Any) -> DeleteProduct:
        query = gql(
            """
            mutation DeleteProduct($input: ProductDeleteInput!) {
              productDelete(input: $input) {
                deletedProductId
                userErrors {
                  field
                  message
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="DeleteProduct", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteProduct.model_validate(data)
