# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class CurrentBulkOperation(BaseModel):
    current_bulk_operation: Optional["CurrentBulkOperationCurrentBulkOperation"] = (
        Field(alias="currentBulkOperation")
    )


class CurrentBulkOperationCurrentBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus
    object_count: int = Field(alias="objectCount")
    url: Optional[AnyUrl]
    partial_data_url: Optional[AnyUrl] = Field(alias="partialDataUrl")


CurrentBulkOperation.model_rebuild()
