# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class CurrentBulkOperation(BaseModel):
    current_bulk_operation: Optional["CurrentBulkOperationCurrentBulkOperation"] = (
        Field(alias="currentBulkOperation")
    )


class CurrentBulkOperationCurrentBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus
    object_count: int = Field(alias="objectCount")
    url: Optional[AnyUrl]
    partial_data_url: Optional[AnyUrl] = Field(alias="partialDataUrl")


CurrentBulkOperation.model_rebuild()
