# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteProduct(BaseModel):
    product_delete: Optional["DeleteProductProductDelete"] = Field(
        alias="productDelete"
    )


class DeleteProductProductDelete(BaseModel):
    deleted_product_id: Optional[str] = Field(alias="deletedProductId")
    user_errors: List["DeleteProductProductDeleteUserErrors"] = Field(
        alias="userErrors"
    )


class DeleteProductProductDeleteUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


DeleteProduct.model_rebuild()
DeleteProductProductDelete.model_rebuild()
