# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql

from decimal import Decimal
from typing import List, Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel
from .enums import CurrencyCode


class MediaImageFields(BaseModel):
    id: str
    alt: Optional[str]
    original_source: Optional["MediaImageFieldsOriginalSource"] = Field(
        alias="originalSource"
    )
    preview: Optional["MediaImageFieldsPreview"]


class MediaImageFieldsOriginalSource(BaseModel):
    url: Optional[AnyUrl]


class MediaImageFieldsPreview(BaseModel):
    image: Optional["MediaImageFieldsPreviewImage"]


class MediaImageFieldsPreviewImage(BaseModel):
    url: AnyUrl


class MetafieldFields(BaseModel):
    id: str
    key: str
    value: str


class UserErrorFields(BaseModel):
    field: Optional[List[str]]
    message: str


class VariantFields(BaseModel):
    id: str
    price: Decimal
    sku: Optional[str]
    barcode: Optional[str]
    inventory_item: "VariantFieldsInventoryItem" = Field(alias="inventoryItem")


class VariantFieldsInventoryItem(BaseModel):
    unit_cost: Optional["VariantFieldsInventoryItemUnitCost"] = Field(alias="unitCost")
    measurement: "VariantFieldsInventoryItemMeasurement"


class VariantFieldsInventoryItemUnitCost(BaseModel):
    amount: Decimal
    currency_code: CurrencyCode = Field(alias="currencyCode")


class VariantFieldsInventoryItemMeasurement(BaseModel):
    weight: Optional["VariantFieldsInventoryItemMeasurementWeight"]


class VariantFieldsInventoryItemMeasurementWeight(BaseModel):
    value: float


MediaImageFields.model_rebuild()
MetafieldFields.model_rebuild()
UserErrorFields.model_rebuild()
VariantFields.model_rebuild()
