# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetProductIds(BaseModel):
    products: "GetProductIdsProducts"


class GetProductIdsProducts(BaseModel):
    page_info: "GetProductIdsProductsPageInfo" = Field(alias="pageInfo")
    edges: List["GetProductIdsProductsEdges"]


class GetProductIdsProductsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetProductIdsProductsEdges(BaseModel):
    cursor: str
    node: "GetProductIdsProductsEdgesNode"


class GetProductIdsProductsEdgesNode(BaseModel):
    id: str


GetProductIds.model_rebuild()
GetProductIdsProducts.model_rebuild()
GetProductIdsProductsEdges.model_rebuild()
