# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode, ProductStatus


class GetProducts(BaseModel):
    products: "GetProductsProducts"


class GetProductsProducts(BaseModel):
    page_info: "GetProductsProductsPageInfo" = Field(alias="pageInfo")
    edges: List["GetProductsProductsEdges"]


class GetProductsProductsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetProductsProductsEdges(BaseModel):
    cursor: str
    node: "GetProductsProductsEdgesNode"


class GetProductsProductsEdgesNode(BaseModel):
    id: str
    title: str
    description_html: Any = Field(alias="descriptionHtml")
    vendor: str
    product_type: str = Field(alias="productType")
    status: ProductStatus
    total_inventory: int = Field(alias="totalInventory")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    media: "GetProductsProductsEdgesNodeMedia"
    variants: "GetProductsProductsEdgesNodeVariants"
    metafields: "GetProductsProductsEdgesNodeMetafields"


class GetProductsProductsEdgesNodeMedia(BaseModel):
    edges: List["GetProductsProductsEdgesNodeMediaEdges"]


class GetProductsProductsEdgesNodeMediaEdges(BaseModel):
    node: "GetProductsProductsEdgesNodeMediaEdgesNode"


class GetProductsProductsEdgesNodeMediaEdgesNode(BaseModel):
    typename__: Literal["ExternalVideo", "Media", "MediaImage", "Model3d", "Video"] = (
        Field(alias="__typename")
    )
    alt: Optional[str]
    preview: Optional["GetProductsProductsEdgesNodeMediaEdgesNodePreview"]


class GetProductsProductsEdgesNodeMediaEdgesNodePreview(BaseModel):
    image: Optional["GetProductsProductsEdgesNodeMediaEdgesNodePreviewImage"]


class GetProductsProductsEdgesNodeMediaEdgesNodePreviewImage(BaseModel):
    url: Any


class GetProductsProductsEdgesNodeVariants(BaseModel):
    edges: List["GetProductsProductsEdgesNodeVariantsEdges"]


class GetProductsProductsEdgesNodeVariantsEdges(BaseModel):
    node: "GetProductsProductsEdgesNodeVariantsEdgesNode"


class GetProductsProductsEdgesNodeVariantsEdgesNode(BaseModel):
    id: str
    price: Any
    sku: Optional[str]
    barcode: Optional[str]
    inventory_item: "GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItem" = (
        Field(alias="inventoryItem")
    )


class GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItem(BaseModel):
    unit_cost: Optional[
        "GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemUnitCost"
    ] = Field(alias="unitCost")
    measurement: "GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemMeasurement"


class GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemUnitCost(BaseModel):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemMeasurement(BaseModel):
    weight: Optional[
        "GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemMeasurementWeight"
    ]


class GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemMeasurementWeight(
    BaseModel
):
    value: float


class GetProductsProductsEdgesNodeMetafields(BaseModel):
    edges: List["GetProductsProductsEdgesNodeMetafieldsEdges"]


class GetProductsProductsEdgesNodeMetafieldsEdges(BaseModel):
    node: "GetProductsProductsEdgesNodeMetafieldsEdgesNode"


class GetProductsProductsEdgesNodeMetafieldsEdgesNode(BaseModel):
    id: str
    key: str
    value: str


GetProducts.model_rebuild()
GetProductsProducts.model_rebuild()
GetProductsProductsEdges.model_rebuild()
GetProductsProductsEdgesNode.model_rebuild()
GetProductsProductsEdgesNodeMedia.model_rebuild()
GetProductsProductsEdgesNodeMediaEdges.model_rebuild()
GetProductsProductsEdgesNodeMediaEdgesNode.model_rebuild()
GetProductsProductsEdgesNodeMediaEdgesNodePreview.model_rebuild()
GetProductsProductsEdgesNodeVariants.model_rebuild()
GetProductsProductsEdgesNodeVariantsEdges.model_rebuild()
GetProductsProductsEdgesNodeVariantsEdgesNode.model_rebuild()
GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItem.model_rebuild()
GetProductsProductsEdgesNodeVariantsEdgesNodeInventoryItemMeasurement.model_rebuild()
GetProductsProductsEdgesNodeMetafields.model_rebuild()
GetProductsProductsEdgesNodeMetafieldsEdges.model_rebuild()
