# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationErrorCode, BulkOperationStatus


class GetBulkOperationStatus(BaseModel):
    current_bulk_operation: Optional["GetBulkOperationStatusCurrentBulkOperation"] = (
        Field(alias="currentBulkOperation")
    )


class GetBulkOperationStatusCurrentBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus
    error_code: Optional[BulkOperationErrorCode] = Field(alias="errorCode")
    created_at: Any = Field(alias="createdAt")
    completed_at: Optional[Any] = Field(alias="completedAt")
    object_count: Any = Field(alias="objectCount")
    file_size: Optional[Any] = Field(alias="fileSize")
    url: Optional[Any]


GetBulkOperationStatus.model_rebuild()
