# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List

from .base_model import BaseModel


class GetLocations(BaseModel):
    locations: "GetLocationsLocations"


class GetLocationsLocations(BaseModel):
    nodes: List["GetLocationsLocationsNodes"]


class GetLocationsLocationsNodes(BaseModel):
    id: str


GetLocations.model_rebuild()
GetLocationsLocations.model_rebuild()
