# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql/shopify

from typing import List

from .base_model import BaseModel


class GetLocations(BaseModel):
    locations: "GetLocationsLocations"


class GetLocationsLocations(BaseModel):
    nodes: List["GetLocationsLocationsNodes"]


class GetLocationsLocationsNodes(BaseModel):
    id: str


GetLocations.model_rebuild()
GetLocationsLocations.model_rebuild()
