# Generated by ariadne-codegen
# Source: /opt/project/addons/product_connect/graphql

__all__ = [
    "CURRENT_BULK_OPERATION_GQL",
    "DELETE_PRODUCT_GQL",
    "GET_LOCATIONS_GQL",
    "GET_ORDERS_GQL",
    "GET_ORDER_IDS_GQL",
    "GET_PRODUCTS_GQL",
    "GET_PRODUCT_IDS_GQL",
    "PRODUCT_SET_BULK_RUN_GQL",
    "PRODUCT_SET_GQL",
    "STAGED_UPLOADS_CREATE_GQL",
    "UPDATE_PUBLICATIONS_GQL",
]

STAGED_UPLOADS_CREATE_GQL = """
mutation StagedUploadsCreate($input: [StagedUploadInput!]!) {
  stagedUploadsCreate(input: $input) {
    stagedTargets {
      url
      parameters {
        name
        value
      }
      resourceUrl
    }
    userErrors {
      field
      message
    }
  }
}
"""

PRODUCT_SET_BULK_RUN_GQL = """
mutation ProductSetBulkRun($mutation: String!, $stagedUploadPath: String!) {
  bulkOperationRunMutation(
    mutation: $mutation
    stagedUploadPath: $stagedUploadPath
  ) {
    bulkOperation {
      id
      status
    }
    userErrors {
      field
      message
    }
  }
}
"""

CURRENT_BULK_OPERATION_GQL = """
query CurrentBulkOperation {
  currentBulkOperation {
    id
    status
    objectCount
    url
    partialDataUrl
  }
}
"""

GET_ORDER_IDS_GQL = """
query GetOrderIds($cursor: String, $limit: Int!, $query: String) {
  orders(first: $limit, after: $cursor, query: $query, sortKey: UPDATED_AT) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
    }
  }
}
"""

GET_ORDERS_GQL = """
query GetOrders($cursor: String, $limit: Int!, $query: String) {
  orders(first: $limit, after: $cursor, query: $query, sortKey: UPDATED_AT) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...OrderFields
    }
  }
}

fragment AddressFields on MailingAddress {
  id
  name
  address1
  address2
  city
  provinceCode
  countryCodeV2
  zip
  phone
}

fragment MetafieldFields on Metafield {
  id
  key
  value
}

fragment MoneyFields on MoneyV2 {
  amount
  currencyCode
}

fragment OrderFields on Order {
  id
  name
  createdAt
  updatedAt
  processedAt
  closedAt
  cancelledAt
  currencyCode
  totalPriceSet {
    presentmentMoney {
      ...MoneyFields
    }
  }
  subtotalPriceSet {
    presentmentMoney {
      ...MoneyFields
    }
  }
  totalShippingPriceSet {
    presentmentMoney {
      ...MoneyFields
    }
  }
  customer {
    id
    defaultEmailAddress {
      emailAddress
    }
    firstName
    lastName
  }
  shippingAddress {
    ...AddressFields
  }
  billingAddress {
    ...AddressFields
  }
  lineItems(first: 250) {
    nodes {
      ...OrderLineItemFields
    }
  }
  metafields(first: 15, namespace: "custom") {
    nodes {
      ...MetafieldFields
    }
  }
}

fragment OrderLineItemFields on LineItem {
  id
  sku
  quantity
  name
  variant {
    id
  }
  originalUnitPriceSet {
    presentmentMoney {
      ...MoneyFields
    }
    shopMoney {
      ...MoneyFields
    }
  }
  customAttributes {
    key
    value
  }
}
"""

GET_PRODUCT_IDS_GQL = """
query GetProductIds($cursor: String, $limit: Int!, $query: String) {
  products(first: $limit, after: $cursor, query: $query, sortKey: UPDATED_AT) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
    }
  }
}
"""

GET_PRODUCTS_GQL = """
query GetProducts($cursor: String, $limit: Int!, $query: String) {
  products(first: $limit, after: $cursor, query: $query, sortKey: UPDATED_AT) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      title
      descriptionHtml
      vendor
      productType
      status
      totalInventory
      createdAt
      updatedAt
      media(first: 250, sortKey: POSITION) {
        nodes {
          __typename
          status
          ...MediaImageFields
        }
      }
      variants(first: 1) {
        nodes {
          ...VariantFields
        }
      }
      metafields(first: 15, namespace: "custom") {
        nodes {
          ...MetafieldFields
        }
      }
    }
  }
}

fragment MediaImageFields on MediaImage {
  id
  alt
  originalSource {
    url
  }
  preview {
    image {
      url
    }
  }
}

fragment MetafieldFields on Metafield {
  id
  key
  value
}

fragment VariantFields on ProductVariant {
  id
  price
  sku
  barcode
  inventoryItem {
    unitCost {
      amount
      currencyCode
    }
    measurement {
      weight {
        value
      }
    }
  }
}
"""

GET_LOCATIONS_GQL = """
query GetLocations {
  locations(first: 5) {
    nodes {
      id
    }
  }
}
"""

PRODUCT_SET_GQL = """
mutation ProductSet($identifier: ProductSetIdentifiers, $input: ProductSetInput!) {
  productSet(identifier: $identifier, input: $input) {
    product {
      id
      updatedAt
      variants(first: 1) {
        nodes {
          ...VariantFields
        }
      }
      metafields(first: 15, namespace: "custom") {
        nodes {
          ...MetafieldFields
        }
      }
      media(first: 250, sortKey: POSITION) {
        nodes {
          __typename
          status
          ...MediaImageFields
        }
      }
      resourcePublicationsV2(onlyPublished: true, first: 10) {
        nodes {
          publication {
            id
          }
        }
      }
    }
    userErrors {
      field
      message
    }
  }
}

fragment MediaImageFields on MediaImage {
  id
  alt
  originalSource {
    url
  }
  preview {
    image {
      url
    }
  }
}

fragment MetafieldFields on Metafield {
  id
  key
  value
}

fragment VariantFields on ProductVariant {
  id
  price
  sku
  barcode
  inventoryItem {
    unitCost {
      amount
      currencyCode
    }
    measurement {
      weight {
        value
      }
    }
  }
}
"""

UPDATE_PUBLICATIONS_GQL = """
mutation UpdatePublications($id: ID!, $input: [PublicationInput!]!) {
  publishablePublish(id: $id, input: $input) {
    userErrors {
      ...UserErrorFields
    }
  }
}

fragment UserErrorFields on UserError {
  field
  message
}
"""

DELETE_PRODUCT_GQL = """
mutation DeleteProduct($input: ProductDeleteInput!, $synchronous: Boolean = false) {
  productDelete(input: $input, synchronous: $synchronous) {
    deletedProductId
    userErrors {
      ...UserErrorFields
    }
  }
}

fragment UserErrorFields on UserError {
  field
  message
}
"""
