# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class ProductSet(BaseModel):
    product_set: Optional["ProductSetProductSet"] = Field(alias="productSet")


class ProductSetProductSet(BaseModel):
    product: Optional["ProductSetProductSetProduct"]
    user_errors: List["ProductSetProductSetUserErrors"] = Field(alias="userErrors")


class ProductSetProductSetProduct(BaseModel):
    id: str
    variants: "ProductSetProductSetProductVariants"
    metafields: "ProductSetProductSetProductMetafields"
    resource_publications_v_2: "ProductSetProductSetProductResourcePublicationsV2" = (
        Field(alias="resourcePublicationsV2")
    )


class ProductSetProductSetProductVariants(BaseModel):
    edges: List["ProductSetProductSetProductVariantsEdges"]


class ProductSetProductSetProductVariantsEdges(BaseModel):
    node: "ProductSetProductSetProductVariantsEdgesNode"


class ProductSetProductSetProductVariantsEdgesNode(BaseModel):
    id: str


class ProductSetProductSetProductMetafields(BaseModel):
    edges: List["ProductSetProductSetProductMetafieldsEdges"]


class ProductSetProductSetProductMetafieldsEdges(BaseModel):
    node: "ProductSetProductSetProductMetafieldsEdgesNode"


class ProductSetProductSetProductMetafieldsEdgesNode(BaseModel):
    id: str
    key: str


class ProductSetProductSetProductResourcePublicationsV2(BaseModel):
    edges: List["ProductSetProductSetProductResourcePublicationsV2Edges"]


class ProductSetProductSetProductResourcePublicationsV2Edges(BaseModel):
    node: "ProductSetProductSetProductResourcePublicationsV2EdgesNode"


class ProductSetProductSetProductResourcePublicationsV2EdgesNode(BaseModel):
    publication: "ProductSetProductSetProductResourcePublicationsV2EdgesNodePublication"


class ProductSetProductSetProductResourcePublicationsV2EdgesNodePublication(BaseModel):
    id: str


class ProductSetProductSetUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


ProductSet.model_rebuild()
ProductSetProductSet.model_rebuild()
ProductSetProductSetProduct.model_rebuild()
ProductSetProductSetProductVariants.model_rebuild()
ProductSetProductSetProductVariantsEdges.model_rebuild()
ProductSetProductSetProductMetafields.model_rebuild()
ProductSetProductSetProductMetafieldsEdges.model_rebuild()
ProductSetProductSetProductResourcePublicationsV2.model_rebuild()
ProductSetProductSetProductResourcePublicationsV2Edges.model_rebuild()
ProductSetProductSetProductResourcePublicationsV2EdgesNode.model_rebuild()
