# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode, MediaContentType, ProductStatus


class ProductSet(BaseModel):
    product_set: Optional["ProductSetProductSet"] = Field(alias="productSet")


class ProductSetProductSet(BaseModel):
    product: Optional["ProductSetProductSetProduct"]
    user_errors: List["ProductSetProductSetUserErrors"] = Field(alias="userErrors")


class ProductSetProductSetProduct(BaseModel):
    id: str
    title: str
    status: ProductStatus
    vendor: str
    product_type: str = Field(alias="productType")
    handle: str
    description_html: Any = Field(alias="descriptionHtml")
    media: "ProductSetProductSetProductMedia"
    variants: "ProductSetProductSetProductVariants"
    metafields: "ProductSetProductSetProductMetafields"


class ProductSetProductSetProductMedia(BaseModel):
    nodes: List[
        Annotated[
            Union[
                "ProductSetProductSetProductMediaNodesMedia",
                "ProductSetProductSetProductMediaNodesMediaImage",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class ProductSetProductSetProductMediaNodesMedia(BaseModel):
    typename__: Literal["ExternalVideo", "Media", "Model3d", "Video"] = Field(
        alias="__typename"
    )
    alt: Optional[str]
    media_content_type: MediaContentType = Field(alias="mediaContentType")


class ProductSetProductSetProductMediaNodesMediaImage(BaseModel):
    typename__: Literal["MediaImage"] = Field(alias="__typename")
    alt: Optional[str]
    media_content_type: MediaContentType = Field(alias="mediaContentType")
    image: Optional["ProductSetProductSetProductMediaNodesMediaImageImage"]


class ProductSetProductSetProductMediaNodesMediaImageImage(BaseModel):
    url: Any


class ProductSetProductSetProductVariants(BaseModel):
    edges: List["ProductSetProductSetProductVariantsEdges"]


class ProductSetProductSetProductVariantsEdges(BaseModel):
    node: "ProductSetProductSetProductVariantsEdgesNode"


class ProductSetProductSetProductVariantsEdgesNode(BaseModel):
    id: str
    price: Any
    sku: Optional[str]
    inventory_item: "ProductSetProductSetProductVariantsEdgesNodeInventoryItem" = Field(
        alias="inventoryItem"
    )


class ProductSetProductSetProductVariantsEdgesNodeInventoryItem(BaseModel):
    unit_cost: Optional[
        "ProductSetProductSetProductVariantsEdgesNodeInventoryItemUnitCost"
    ] = Field(alias="unitCost")
    measurement: "ProductSetProductSetProductVariantsEdgesNodeInventoryItemMeasurement"


class ProductSetProductSetProductVariantsEdgesNodeInventoryItemUnitCost(BaseModel):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class ProductSetProductSetProductVariantsEdgesNodeInventoryItemMeasurement(BaseModel):
    weight: Optional[
        "ProductSetProductSetProductVariantsEdgesNodeInventoryItemMeasurementWeight"
    ]


class ProductSetProductSetProductVariantsEdgesNodeInventoryItemMeasurementWeight(
    BaseModel
):
    value: float


class ProductSetProductSetProductMetafields(BaseModel):
    edges: List["ProductSetProductSetProductMetafieldsEdges"]


class ProductSetProductSetProductMetafieldsEdges(BaseModel):
    node: "ProductSetProductSetProductMetafieldsEdgesNode"


class ProductSetProductSetProductMetafieldsEdgesNode(BaseModel):
    id: str
    key: str
    value: str


class ProductSetProductSetUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


ProductSet.model_rebuild()
ProductSetProductSet.model_rebuild()
ProductSetProductSetProduct.model_rebuild()
ProductSetProductSetProductMedia.model_rebuild()
ProductSetProductSetProductMediaNodesMediaImage.model_rebuild()
ProductSetProductSetProductVariants.model_rebuild()
ProductSetProductSetProductVariantsEdges.model_rebuild()
ProductSetProductSetProductVariantsEdgesNode.model_rebuild()
ProductSetProductSetProductVariantsEdgesNodeInventoryItem.model_rebuild()
ProductSetProductSetProductVariantsEdgesNodeInventoryItemMeasurement.model_rebuild()
ProductSetProductSetProductMetafields.model_rebuild()
ProductSetProductSetProductMetafieldsEdges.model_rebuild()
