# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class RunBulkOperation(BaseModel):
    bulk_operation_run_mutation: Optional[
        "RunBulkOperationBulkOperationRunMutation"
    ] = Field(alias="bulkOperationRunMutation")


class RunBulkOperationBulkOperationRunMutation(BaseModel):
    bulk_operation: Optional[
        "RunBulkOperationBulkOperationRunMutationBulkOperation"
    ] = Field(alias="bulkOperation")
    user_errors: List["RunBulkOperationBulkOperationRunMutationUserErrors"] = Field(
        alias="userErrors"
    )


class RunBulkOperationBulkOperationRunMutationBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus


class RunBulkOperationBulkOperationRunMutationUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


RunBulkOperation.model_rebuild()
RunBulkOperationBulkOperationRunMutation.model_rebuild()
