# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class RunBulkOperation(BaseModel):
    bulk_operation_run_query: Optional["RunBulkOperationBulkOperationRunQuery"] = Field(
        alias="bulkOperationRunQuery"
    )


class RunBulkOperationBulkOperationRunQuery(BaseModel):
    bulk_operation: Optional["RunBulkOperationBulkOperationRunQueryBulkOperation"] = (
        Field(alias="bulkOperation")
    )
    user_errors: List["RunBulkOperationBulkOperationRunQueryUserErrors"] = Field(
        alias="userErrors"
    )


class RunBulkOperationBulkOperationRunQueryBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus


class RunBulkOperationBulkOperationRunQueryUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


RunBulkOperation.model_rebuild()
RunBulkOperationBulkOperationRunQuery.model_rebuild()
