# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class StagedUploadsCreate(BaseModel):
    staged_uploads_create: Optional["StagedUploadsCreateStagedUploadsCreate"] = Field(
        alias="stagedUploadsCreate"
    )


class StagedUploadsCreateStagedUploadsCreate(BaseModel):
    staged_targets: Optional[
        List["StagedUploadsCreateStagedUploadsCreateStagedTargets"]
    ] = Field(alias="stagedTargets")
    user_errors: List["StagedUploadsCreateStagedUploadsCreateUserErrors"] = Field(
        alias="userErrors"
    )


class StagedUploadsCreateStagedUploadsCreateStagedTargets(BaseModel):
    url: Optional[Any]
    parameters: List["StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters"]
    resource_url: Optional[Any] = Field(alias="resourceUrl")


class StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters(BaseModel):
    name: str
    value: str


class StagedUploadsCreateStagedUploadsCreateUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


StagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreateStagedTargets.model_rebuild()
