# type: ignore
# noinspection PyUnreachableCode
# noinspection PyUnresolvedReferences
# noinspection PyPackageRequirements
# noinspection SpellCheckingInspection
# noinspection PyMissingTypeHints
# noinspection PyUnusedLocal
# noinspection PyPep8Naming
# noinspection PyMethodMayBeStatic
# Generated by ariadne-codegen
# Source: /volumes/addons/product_connect/graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdatePublications(BaseModel):
    publishable_publish: Optional["UpdatePublicationsPublishablePublish"] = Field(
        alias="publishablePublish"
    )


class UpdatePublicationsPublishablePublish(BaseModel):
    user_errors: List["UpdatePublicationsPublishablePublishUserErrors"] = Field(
        alias="userErrors"
    )


class UpdatePublicationsPublishablePublishUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


UpdatePublications.model_rebuild()
UpdatePublicationsPublishablePublish.model_rebuild()
