name: Deploy to Testing
on:
  workflow_dispatch:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale VPN
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.70.0
      - name: Wait for Tailscale
        run: |
          # Ping loop
          host="${{ vars.TESTING_SERVER }}"
          count=0
          max_attempts=30
          while ! ping -c 1 -W 1 $host > /dev/null 2>&1; do
            count=$((count+1))
            echo "Attempt $count: Ping to $host failed, retrying..."
            if [ $count -ge $max_attempts ]; then
              echo "Failed to reach $host after $max_attempts attempts, stopping."
              exit 1
            fi
            sleep 1
          done
          echo "Ping to $host successful."
        shell: bash
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.TESTING_SERVER }} >> ~/.ssh/known_hosts
        shell: bash
      - name: Clone & Install
        run: |
          ssh ${{ vars.TESTING_USER }}@${{ vars.TESTING_SERVER }} 'cd /opt/odoo/odoo-addons/product_connect; sudo -u odoo git pull; sudo systemctl restart odoo'
        shell: bash
      - name: Wait for website to be up (Python)
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python - <<'EOF'
          import time, sys
          import requests
          import os
      
          url = f"http://{os.environ.get('TESTING_SERVER')}:8069/web/login"
          print("TESTING_SERVER:", os.environ.get("TESTING_SERVER"), flush=True)
          print("URL:", url, flush=True)
          max_attempts = 100
          attempt = 0
      
          while attempt < max_attempts:
              try:
                  response = requests.get(url, timeout=10)
                  if response.status_code == 200:
                      print("Received 200 OK")
                      sys.exit(0)
                  else:
                      print(f"Attempt {attempt+1} failed: {e}", flush=True)
              except Exception as e:
                  print(f"Attempt {attempt+1} failed: {e}")
              attempt += 1
              time.sleep(5)
          print(f"Failed to get 200 OK after {max_attempts} attempts")
          sys.exit(1)
          EOF
        shell: bash